language: node_js
# nodejs版本
node_js:
  - '10'

# S: Build Lifecycle
install:
  - yarn install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - yarn test

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
env:
  global:
